### ISSUE TITLE
docker compose 报错

### ISSUE THREAD

**Issue by tanpengsccd** [yym68686/ChatGPT-Telegram-Bot#4]
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/13959880/206910851-ea32693e-4c64-4960-8b3f-414fc19bd5b5.png">

```
version: "3.5"
services:
  chatgptbot:
    container_name: chatgptbot
    image: yym68686/chatgpt:1.0
    environment:
      # telegram
      # - NICK=
      - BOT_TOKEN=554脱密03:AAFwdPKw脱密plCbE1PeGuQ
      - WEB_HOOK=https://chatgpt.脱密.work/
      # openai session
      # - session_token=
      - email=[脱密]
      - password=[脱密]
    ports:
      - 20080:8080
```
