### ISSUE TITLE
Enchancement - Add Group Folder/Button to models in bot 

### ISSUE THREAD

**Issue by ratu-sh** [yym68686/ChatGPT-Telegram-Bot#63]
Problem - When you use in bot many different providers with many different models - it is very hard to find  needed one without sorting and filtering from one shared big list of models. 

Enchancement  - i think it could be good idea to add ability to group models in bot by your choice with environment variables.
So when you click on "/info - change model" - you will see not one shared list of all models - but several buttons with group names. and when you click button - than you see list of models only from that group.

for example you may group models by provider name (openrouter, grok, google, others), or by models family (gemini, llama, chatgpt, others) or by any another way.

for it purpose you can add some variables in environment like:

```bash
Environment="GET_MODELS=False"
#Environment="CUSTOM_MODELS=-all,***,***"
Environment="GROUP_MODELS=True"
Environment="GROUP_NAMES="gemini,llama,chatgpt,others"
Environment="GROUP_1=model-1-example,model-2-example"
Environment="GROUP_x=***"
Environment="GROUP_4=model-3-example,model-4-example"
```

**Comment by yym68686** [comment]
Hello, I don't think adding too many environment variables is a good idea. I cannot accept adding so many environment variables just to meet this one requirement. I hope there is a better way.

**Comment by ratu-sh** [comment]
> Hello, I don't think adding too many environment variables is a good idea. I cannot accept adding so many environment variables just to meet this one requirement. I hope there is a better way.

than we can add in Environment only 1 variable with `groups.yaml` (or json or txt) path like that

```bash
Environment="GROUP_MODELS_PATH=\path\to\groups.yaml"
```

and `groups.yaml` will have this structure:

```yaml
  - group: group-1
    button_name: openai
    models:
      - gpt-3.5-turbo
      - gtp-4o-mini
      - ***

  - group: group-2
    button_name: meta
    models:
      - llama-3.1-7b
      - llama-3.2-80b
      - ***
      
- group: group-3
    button_name: gemini
    models:
      - gemini-1.5-flash
      - gemini-1.5-pro
      - ***
```
